"""CUDA C++ emission for a fused, online-softmax attention kernel."""

from __future__ import annotations

from .ir import AttentionIR, Expr


def emit_expr(expr: Expr) -> str:
    if expr.op == "const":
        if isinstance(expr.value, bool): return "true" if expr.value else "false"
        if isinstance(expr.value, int): return str(expr.value)
        return f"{float(expr.value):.9g}f"
    if expr.op == "var": return str(expr.value)
    if expr.op == "lookup": return f"table_{expr.value}[int({emit_expr(expr.args[0])})]"
    a = emit_expr(expr.args[0]) if expr.args else ""
    b = emit_expr(expr.args[1]) if len(expr.args) > 1 else ""
    infix = {
        "add": "+", "sub": "-", "mul": "*", "div": "/", "lt": "<",
        "le": "<=", "gt": ">", "ge": ">=", "eq": "==", "and": "&&", "or": "||",
    }
    if expr.op in infix: return f"({a} {infix[expr.op]} {b})"
    if expr.op == "neg": return f"(-{a})"
    if expr.op == "not": return f"(!{a})"
    if expr.op == "tanh": return f"tanhf({a})"
    if expr.op == "exp": return f"expf({a})"
    if expr.op == "abs": return f"fabsf({a})"
    if expr.op == "minimum": return f"fminf({a}, {b})"
    if expr.op == "maximum": return f"fmaxf({a}, {b})"
    if expr.op == "select": return f"({a} ? {b} : {emit_expr(expr.args[2])})"
    raise ValueError(f"cannot emit op: {expr.op}")


def _tile_classifier(ir: AttentionIR) -> str:
    bounds = ir.mask_bounds
    if bounds is None:
        return "return 1; // unknown mask: conservatively predicated"
    masked: list[str] = []
    unmasked: list[str] = []
    if bounds.causal:
        masked.append("k0 > q_idx")
        unmasked.append("(k1 - 1) <= q_idx")
    if bounds.window is not None:
        masked.append(f"(k1 - 1) < (q_idx - {bounds.window} + 1)")
        unmasked.append(f"k0 >= (q_idx - {bounds.window} + 1)")
    if not masked:
        return "return 2;"
    return (
        f"if ({' || '.join(masked)}) return 0;\n"
        f"    if ({' && '.join(unmasked)}) return 2;\n"
        "    return 1;"
    )


def generate_cuda(ir: AttentionIR, *, kernel_name: str = "attnc_attention", kv_tile: int = 64) -> str:
    """Generate a correctness-first fused kernel with key-tile mask skipping.

    One warp owns a query row. It computes QK, the score modification, online
    softmax, and PV without materializing the score matrix.
    """
    if ir.layout.kv_layout != "contiguous":
        raise NotImplementedError("paged KV is a documented stretch goal; this backend supports contiguous KV")
    ctype = "half" if ir.layout.dtype == "fp16" else "float"
    load = "__half2float" if ir.layout.dtype == "fp16" else ""
    store = "__float2half_rn" if ir.layout.dtype == "fp16" else ""
    table_params = "".join(f", const float* __restrict__ table_{name}" for name in sorted(ir.tables))
    mask = emit_expr(ir.mask)
    score = emit_expr(ir.score)
    classifier = _tile_classifier(ir)
    load_q = f"{load}(q[q_base + d])" if load else "q[q_base + d]"
    load_k = f"{load}(k[k_base + d])" if load else "k[k_base + d]"
    load_v = f"{load}(v[k_base + d])" if load else "v[k_base + d]"
    store_out = f"{store}(acc[i] / l)" if store else "acc[i] / l"

    return f'''// Generated by attnc. Cacheable key is derived from the optimized IR.
#include <cuda_fp16.h>
#include <math.h>

namespace {{
constexpr int HEAD_DIM = {ir.layout.head_dim};
constexpr int WARP = 32;
constexpr int ITEMS = (HEAD_DIM + WARP - 1) / WARP;
constexpr int KV_TILE = {kv_tile};

__device__ __forceinline__ float warp_sum(float x) {{
    #pragma unroll
    for (int delta = 16; delta > 0; delta >>= 1)
        x += __shfl_down_sync(0xffffffff, x, delta);
    return __shfl_sync(0xffffffff, x, 0);
}}

__device__ __forceinline__ int classify_kv_tile(int q_idx, int k0, int k1) {{
    // 0 = fully masked, 1 = partial/predicated, 2 = fully unmasked.
    {classifier}
}}
}} // namespace

extern "C" __global__ void {kernel_name}(
    const {ctype}* __restrict__ q,
    const {ctype}* __restrict__ k,
    const {ctype}* __restrict__ v,
    {ctype}* __restrict__ out{table_params},
    int B, int HQ, int HKV, int NQ, int NK, int q_offset, float scale) {{
    const int lane = threadIdx.x;
    if (lane >= WARP) return;
    const int row = blockIdx.x;
    const int q_local = row % NQ;
    const int q_idx = q_local + q_offset;
    const int h = (row / NQ) % HQ;
    const int b = row / (NQ * HQ);
    if (b >= B) return;
    const int kh = (h * HKV) / HQ;
    const long long q_base = ((long long)b * HQ * NQ + (long long)h * NQ + q_local) * HEAD_DIM;

    float acc[ITEMS];
    #pragma unroll
    for (int i = 0; i < ITEMS; ++i) acc[i] = 0.0f;
    float m = -INFINITY;
    float l = 0.0f;

    for (int k0 = 0; k0 < NK; k0 += KV_TILE) {{
        const int k1 = min(k0 + KV_TILE, NK);
        const int tile_state = classify_kv_tile(q_idx, k0, k1);
        if (tile_state == 0) continue;
        for (int kv_idx = k0; kv_idx < k1; ++kv_idx) {{
            if (tile_state == 1 && !({mask})) continue;
            const long long k_base = ((long long)b * HKV * NK + (long long)kh * NK + kv_idx) * HEAD_DIM;
            float dot = 0.0f;
            for (int d = lane; d < HEAD_DIM; d += WARP)
                dot += {load_q} * {load_k};
            float score = warp_sum(dot) * scale;
            score = {score};

            const float new_m = fmaxf(m, score);
            const float alpha = (m == -INFINITY) ? 0.0f : expf(m - new_m);
            const float beta = expf(score - new_m);
            l = l * alpha + beta;
            #pragma unroll
            for (int i = 0; i < ITEMS; ++i) {{
                const int d = lane + i * WARP;
                if (d < HEAD_DIM)
                    acc[i] = acc[i] * alpha + beta * {load_v};
            }}
            m = new_m;
        }}
    }}

    const long long out_base = q_base;
    #pragma unroll
    for (int i = 0; i < ITEMS; ++i) {{
        const int d = lane + i * WARP;
        if (d < HEAD_DIM)
            out[out_base + d] = (l == 0.0f) ? ({ctype})0 : ({ctype})({store_out});
    }}
}}
'''
